### ISSUE TITLE
add process driver

### ISSUE THREAD

**Issue by tonistiigi** [tonistiigi/buildx#21]
Add driver that can detect buildkitd in the `$PATH` and run it directly. For example, this driver can be used with #12 . Pidfile should be used for keeping track of the daemon and monitoring its state.

**Comment by errordeveloper** [comment]
> Pidfile should be used for keeping track of the daemon and monitoring its state.

Process management can be tricky, perhaps `docker-container` driver does a pretty good job at this!

Perhaps this kind of driver might be more feasible for a setting where the `buildkitd` runs in foreground for a single build and expected to exit right away?

**Comment by crazy-max** [comment]
I thought a bit more about this driver, quick notes:

* Check buildkitd in path
  * If not available we can download latest buildkit release and extract to `~/.docker/buildx/.buildkit/<version>` (use GitHub API to retrieve artifacts)
    * Also be able to set buildkit version through driver-opt
* PID in `~/.docker/buildx/.buildkit/<builder_name>/buildkitd.pid`
* Define default BuildKit Daemon configuration for this driver with defaults (can be default buildkitd-flags too):

```toml
root = "~/.docker/buildx/.buildkit/<builder_name>/state"
insecure-entitlements = [ "network.host", "security.insecure" ] # not sure

[worker.oci]
  enabled = true
  snapshotter = "auto" # overlayfs or native, default value is "auto".
  rootless = true # rootless should be enabled by default (or disabled if "docker buildx create" run as root)
  binary = "~/.docker/buildx/.buildkit/<version>/buildkit-runc"
```
